<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Business\Booking\" />
    <Folder Include="Business\Booking\Interfaces\" />
    <Folder Include="Business\Booking\Services\" />
    <Folder Include="Controllers\" />
    <Folder Include="Domian\Booking\" />
    <Folder Include="Domian\Booking\Interfaces\" />
    <Folder Include="Domian\Booking\Services\" />
    <Folder Include="Dtos\Booking\" />
    <Folder Include="Dtos\Manager\" />
    <Folder Include="Dto\" />
    <Folder Include="Dto\VehicleImage\" />
    <Folder Include="Dto\VehicleSpecification\" />
    <Folder Include="Dto\Vehicle\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Middleware\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
