// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicalApi.Data;

#nullable disable

namespace VehicalApi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260105073205_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicalApi.Entity.RideBooking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<int>("ShowroomId")
                        .HasColumnType("int");

                    b.Property<int>("SlotHour")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.ToTable("RideBookings");
                });

            modelBuilder.Entity("VehicalApi.Entity.Showroom", b =>
                {
                    b.Property<int>("ShowroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShowroomId"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("ShowroomLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShowroomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ShowroomId")
                        .HasName("PK__Showroom__A7726CBB0A7E547B");

                    b.HasIndex("ManagerId");

                    b.HasIndex(new[] { "ContactNumber" }, "UQ__Showroom__570665C6F41D4DD4")
                        .IsUnique();

                    b.HasIndex(new[] { "ShowroomName" }, "UQ__Showroom__C46B526F0EFC64D4")
                        .IsUnique();

                    b.ToTable("Showrooms");
                });

            modelBuilder.Entity("VehicalApi.Entity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .UseCollation("Latin1_General_CS_AS");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CF023086F");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053468E7FA6E")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VehicalApi.Entity.Vehicle", b =>
                {
                    b.Property<int>("VehicalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicalId"));

                    b.Property<DateTime>("AgeInShowroom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("BasePrice")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("shortDescription");

                    b.Property<int>("ShowroomId")
                        .HasColumnType("int");

                    b.Property<int>("StockCount")
                        .HasColumnType("int")
                        .HasColumnName("stockCount");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("YearOfProduction")
                        .HasColumnType("int");

                    b.HasKey("VehicalId")
                        .HasName("PK__Vehicle__1D89FCE1D3A942A5");

                    b.HasIndex("ShowroomId");

                    b.HasIndex(new[] { "AgeInShowroom" }, "IX_Vehicle_AgeInShowroom");

                    b.HasIndex(new[] { "BasePrice" }, "IX_Vehicle_BasePrice");

                    b.HasIndex(new[] { "VehicleName" }, "IX_Vehicle_VehicleName");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("VehicalApi.Entity.VehicleImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageLocation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("ImageId")
                        .HasName("PK__VehicleI__7516F70C3988B832");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleImage", (string)null);
                });

            modelBuilder.Entity("VehicalApi.Entity.VehicleSpecification", b =>
                {
                    b.Property<int>("SpecificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("specificationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecificationId"));

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Engine")
                        .HasColumnType("int")
                        .HasColumnName("engine");

                    b.Property<string>("FuleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fuleType");

                    b.Property<string>("Mileage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PowerOfvehical")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Torque")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("VehicalId")
                        .HasColumnType("int")
                        .HasColumnName("vehicalId");

                    b.HasKey("SpecificationId")
                        .HasName("PK__VehicleS__FC1C560A6A276819");

                    b.HasIndex(new[] { "BodyType" }, "IX_VehicleSpecifications_BodyType");

                    b.HasIndex(new[] { "Engine" }, "IX_VehicleSpecifications_Engine");

                    b.HasIndex(new[] { "FuleType" }, "IX_VehicleSpecifications_FuelType");

                    b.HasIndex(new[] { "VehicalId" }, "IX_VehicleSpecifications_VehicleId");

                    b.ToTable("VehicleSpecifications");
                });

            modelBuilder.Entity("VehicalApi.Entity.Showroom", b =>
                {
                    b.HasOne("VehicalApi.Entity.User", "Manager")
                        .WithMany("Showrooms")
                        .HasForeignKey("ManagerId")
                        .IsRequired()
                        .HasConstraintName("FK__Showrooms__Manag__6383C8BA");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("VehicalApi.Entity.Vehicle", b =>
                {
                    b.HasOne("VehicalApi.Entity.Showroom", "Showroom")
                        .WithMany("Vehicles")
                        .HasForeignKey("ShowroomId")
                        .IsRequired()
                        .HasConstraintName("FK__Vehicle__Showroo__71D1E811");

                    b.Navigation("Showroom");
                });

            modelBuilder.Entity("VehicalApi.Entity.VehicleImage", b =>
                {
                    b.HasOne("VehicalApi.Entity.Vehicle", "Vehicle")
                        .WithMany("VehicleImages")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VehicleImage_Vehicle");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicalApi.Entity.VehicleSpecification", b =>
                {
                    b.HasOne("VehicalApi.Entity.Vehicle", "Vehical")
                        .WithMany("VehicleSpecifications")
                        .HasForeignKey("VehicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VehicleSpecification_Vehicle");

                    b.Navigation("Vehical");
                });

            modelBuilder.Entity("VehicalApi.Entity.Showroom", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicalApi.Entity.User", b =>
                {
                    b.Navigation("Showrooms");
                });

            modelBuilder.Entity("VehicalApi.Entity.Vehicle", b =>
                {
                    b.Navigation("VehicleImages");

                    b.Navigation("VehicleSpecifications");
                });
#pragma warning restore 612, 618
        }
    }
}
